# Generated by Django 4.1.4 on 2025-05-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_readinglist_options_readinglist_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('arts', 'ARTS'), ('games', 'GAMES'),('technology', 'TECHNOLOGY'), ('business', 'BUSINESS'), ('sports', 'SPORTS'), ('science', 'SCIENCE')], max_length=20),
        ),
    ]
