# Generated by Django 4.1.4 on 2025-05-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('arts', 'ARTS'), ('games', 'GAMES'), ('health', 'HEALTH'), ('technology', 'TECHNOLOGY'), ('business', 'BUSINESS'), ('sports', 'SPORTS'), ('science', 'SCIENCE')], max_length=20),
        ),
    ]
